[toolchain]
package_manager = "yarn"


[features]
resolution = true
skip-lint = false
idl-build = ["anchor-spl/idl-build"]

[programs.localnet]
dextik = "2DgdaYVe3y38aHABcbyJxa4sKbirWWkW8P4UaTWD2SNk"

[programs.devnet]
dextik = "2DgdaYVe3y38aHABcbyJxa4sKbirWWkW8P4UaTWD2SNk"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
